[workspace]
resolver = "2"
members = [
"org-parser",
"org-exporter",
"parse-org",
]


# [package]
# name = "org-rust"
# version = "0.1.0"
# edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html



