[package]
name = "org-exporter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
latex2mathml = "0.2.3"
org-parser = { path = "../org-parser" }
